### ISSUE TITLE
Error: self signed certificate

### ISSUE THREAD

**Issue by Calrain** [arangodb/foxx-cli#10]
ArangoDB 3.2.8 on Windows 2016
ArangoDB is using a self-signed certificate created with OpenSSL and running on port 8530 with port 8529 disabled.
The ArangoDB server is accessible via a web UI.

I have saved a server with the command:
`foxx server set myserver https://{uid}:{password}@myserver.corp.local:8530`

I validated that the contents of my `.foxxrc` properly decoded the command and is storing the parameters properly.

Running the command:
`foxx --server myserver list` from the command line and the response is:

    Sorry! An unexpected error occurred. This is likely a bug in foxx-cli.
    Please open an issue at https://github.com/arangodb/foxx-cli/issues with a full copy of the following
    error message and a description of what you were trying to do when this problem occured.
    
    Error: self signed certificate
        at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)
        at emitNone (events.js:106:13)
        at TLSSocket.emit (events.js:208:7)
        at TLSSocket._finishInit (_tls_wrap.js:637:8)
        at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38)
    
    We apologize for the inconvenience.

**Comment by pluma** [comment]
This is a limitation of Node.js. The certificate check can be disabled by setting the env `NODE_TLS_REJECT_UNAUTHORIZED` to something falsey (e.g. "0") but this is strongly discouraged for production use. There's no easy way to disable these checks per server and it's strongly discouraged to disable these checks ever.

If at all possible I'd recommend either using HTTP over an SSH tunnel or using a real certificate (via letsencrypt).

**Comment by Calrain** [comment]
@pluma Thanks for updating the ticket. Do you have information about what bug or issue this is within Node? I'm wondering if I was to generate an SSL certificate with additional attributes if we could get by the Node error. Did you have a link or issue as to how Node is failing with this validation?
