### ISSUE TITLE
Errors using bundle / zip

### ISSUE THREAD

**Issue by davidmw** [arangodb/foxx-cli#14]
On Mac OSX, running in terminal:

> foxx zip -o test

Sorry! An unexpected error occurred. This is likely a bug in foxx-cli.
Please open an issue at https://github.com/arangodb/foxx-cli/issues with a full copy of the following error message and a description of what you were trying to do when this problem occured.

TypeError: bundle is not a function
    at Object.handler (/usr/local/lib/node_modules/foxx-cli/src/cmds/bundle.js:86:11)
    at <anonymous>

We apologize for the inconvenience.

**Comment by pluma** [comment]
This has probably been fixed in master. I'll cut a new release asap.

**Comment by pluma** [comment]
0.3.0 is out which should fix this.
