### ISSUE TITLE
Usage not really usage

### ISSUE THREAD

**Issue by Thijxx** [arangodb/foxx-cli#23]
The Usage part in the README does not really describe any usage. It point to more Help sources.
Adding a few detailed examples would be an enormous help to new users.

**Comment by pluma** [comment]
Yupp, that's true. We have an internal ticket for adding additional documentation, including a few usage examples. The CLI does bring a lot of examples for the individual commands, though, so the `--help` flag is a good place to start until then.

**Comment by Thijxx** [comment]
Feel free to close this issue, I'm leaving this here for others who do not RTFM and like to work by examples :D

```
# Set server alias to pp
foxx server set pp http://localhost:32769

# List server
foxx --server pp ls

# Show mount
foxx show --server pp --database dbname /mountname

# Make service
cd service_dir
foxx bundle -f -o ../service.zip
cd ..

# Upgrade service (does not install when new unfortunately)
foxx upgrade --server pp --database dbname /mountname service.zip

# Set development mode
foxx set-dev --server pp --database dbname /mountname
```

**Comment by pluma** [comment]
We've expanded a bit on the usage section now that the generator is working. We'll still add more information for the documentation though.
