### ISSUE TITLE
Yes Sir

### ISSUE THREAD

**Issue by ghost** [arangodb/foxx-cli#24]
Uploading a file with bugs in it as a service is no problem. It does not really matter what the javascript contains, it is always accepted. When I use the same file using the web interface to upload it I get an error. So foxx cli is somehow circumventing the checks.

Command I use
`foxx upgrade --server pp --database piekenpijp /incoming alldocs.zip`

**Comment by mpv1989** [comment]
Hi @Thijxx ,

we are not able to reproduce the problem you described. Could you send us an example service that leads to the behavior you described?

Thanks & best
Mark

**Comment by Thijxx** [comment]
I'm having trouble reproducing the problem myself, I will try again in a few days on the machine I had this issue with.

This is what I did:

```
cd alldocs
foxx bundle -f -o ../alldocs.zip
cd ..
foxx upgrade --server pp --database piekenpijp /incoming alldocs.zip
foxx set-dev --server pp --database piekenpijp /incoming
```

**Comment by pluma** [comment]
We haven't heard from you in a while so I'm guessing you weren't able to reproduce the problem anymore. Feel free to reopen this issue if the problem persists.
