### ISSUE TITLE
foxx run error

### ISSUE THREAD

**Issue by camargo** [arangodb/foxx-cli#29]
`foxx-cli` version: `1.1.3`
`ArangoDB` version: `3.3.8`

When using:

`foxx run /some-service some-script --server http://localhost:8529 --database Test`

 I am seeing an error: 

```
Unexpected ArangoDB error (Code: 400):
Unexpected end of JSON input
```

`/some-service` is mounted in the `Test` database and has a `some-script`.

Please let me know if this is my error or yours. Thanks.

**Comment by mpv1989** [comment]
Hi @camargo,

this is a bug in ArangoDB which does not allow an empty request body for the route to run scripts. I already created a [PR](https://github.com/arangodb/arangodb/pull/5305) to fix it.

As a workaround you can pass an empty object as a parameter to the script.

```
foxx run /some-service some-script {} --server http://localhost:8529 --database Test
```

best
Mark

**Comment by camargo** [comment]
@mpv1989 Thank you!
