### ISSUE TITLE
foxx install command doesn't support "unix://" socket connections

### ISSUE THREAD

**Issue by vlabmichl** [arangodb/foxx-cli#32]
It seems that the FOXX-CLI package doesn't support "unix://" socket connections.

While trying to use the FOXX-CLI package within a Docker Container for automatic deployment of services at buildtime I encountered the following problem:
* when I try to install / deploy my FOXX-Service with the command `foxx install ...` the command states that the "unix://" scheme is invalid/unsupported.
The output of `foxx install --help` confirms that as there are no options or examples listed using the "unix://" scheme.

As mentioned earlier in https://github.com/arangodb/arangodb/issues/4393 there seems to a problem with the presence of the loopback interface at the time when the Docker "entrypoint script" is executed.
In consequence the default TCP/HTTP scheme "http://localhost:8529" isn't working.
The "entrypoint script" uses hereing the "unix://" scheme to solve this issue when connections to the server shall be established.

When I connect into the running container the TCP scheme is available and I can run the FOXX-CLI with no problems.

**Comment by pluma** [comment]
That's correct. Foxx CLI uses arangojs internally which doesn't currently support unix sockets.

Have you tried the [arangodb-preview](https://hub.docker.com/r/arangodb/arangodb-preview/) images? As I understand it, they have now baked foxx-cli into them and the plan is for those images to appear in the stable registry eventually.

/cc @neunhoef who might know more about this

**Comment by pluma** [comment]
v1.3.0 fixes this by adding unix socket support for ArangoDB endpoint URLs.
