### ISSUE TITLE
TypeError: Cannot read property 'isDirectory' of null

### ISSUE THREAD

**Issue by ixxie** [arangodb/foxx-cli#34]
I am trying to install some Foxx microservices into an ArangoDB based Docker image, something like:

```Dockerfile
# escape=`
FROM arangodb:latest

WORKDIR /

# Enable https support for apt-get
RUN apt-get update `
    && apt-get install -y apt-transport-https ca-certificates

# Enable node.js & yarn repositories
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

# Install yarn
RUN apt-get update `
    && apt-get install -y yarn `
    && rm -rf /var/lib/apt/lists/*

# Install Foxx CLI
RUN yarn global add foxx-cli

# Install Foxx microservices
RUN mkdir foxx
COPY ./foxx/* foxx/
RUN for service in foxx/*; do foxx install $service; done
```

but I get the following error:

```
TypeError: Cannot read property 'isDirectory' of null
    at /usr/local/share/.config/yarn/global/node_modules/foxx-cli/dist/util/fs.js:58:21
    at Generator.next (<anonymous>)
    at step (/usr/local/share/.config/yarn/global/node_modules/foxx-cli/dist/util/fs.js:3:191)
    at /usr/local/share/.config/yarn/global/node_modules/foxx-cli/dist/util/fs.js:3:361
    at <anonymous>
```

Note that this installed version 1.3.0 of the foxx-cli.

**Comment by pluma** [comment]
That's a bug (i.e. it should provide a more meaningful error message) but the cause seems to be that it gets an invalid source path.

I'm not fluent in Docker or bash. Can you clarify what the last line of your Docker file does?

It looks like it's running a command like this:
`foxx install name-of-subfolder`

Keep in mind that `foxx install` takes two positional argument:
* the first argument is the mount path (i.e. relative to the database, what path the service's routes will be mounted at; this needs to be unique per database and is used to distinguish the installed services)
* the second (optional) argument is the file path from which the service should be bundled and uploaded (this defaults to the current directory, i.e. `.` but can be an arbitrary file path or directory path)

It looks like you're not passing the mount path and try to only pass the local directory path.

**Comment by ixxie** [comment]
Indeed it seems that was the issue!

For completeness, the Dockerfile above installs foxx-cli on top of ArangoDB and then installs some Foxx microservices. *Since foxx-cli is included with ArangoDB, the installation steps are no longer needed*. You can now do:

```
FROM arangodb:latest

WORKDIR /

RUN mkdir -p foxx
COPY ./foxx/ foxx/

COPY init-script.sh /docker-entrypoint-initdb.d/
```

where `init-script.sh` installs the Foxx services
```
#!/bin/sh

pass=$ARANGO_ROOT_PASSWORD

echo $pass | foxx -u root -P --database dbName install /mountpoint /foxx/service
```

**Comment by tomterl** [comment]
Side note: This error also pops up if there is an (emacs) temp-file present (unsaved changes in a file), better reporting would indeed have shortened the time needed to find that out :); the error is not in install, but bundle (and install calls bundle).

**Comment by fschoell** [comment]
Having this issue on macOS 12.0.1 running foxx-cli 2.0.0:

```
$ foxx upgrade --server prod /v0
Sorry! An unexpected error occurred. This is likely a bug in foxx-cli.
Please open an issue at https://github.com/arangodb/foxx-cli/issues with a full copy of the following error message and a description of what you were trying to do when this problem occurred.

TypeError: Cannot read property 'isDirectory' of null
    at /Users/work/Webstorm/arangodb-rest-api/node_modules/foxx-cli/lib/util/fs.js:47:19
    at async Promise.all (index 25)
    at async walk (/Users/work/Webstorm/arangodb-rest-api/node_modules/foxx-cli/lib/util/fs.js:43:5)
    at async Object.gatherFiles (/Users/work/Webstorm/arangodb-rest-api/node_modules/foxx-cli/lib/bundle.js:10:10)
    at async createBundle (/Users/work/Webstorm/arangodb-rest-api/node_modules/foxx-cli/lib/bundle.js:14:17)
    at async bundleToStream (/Users/work/Webstorm/arangodb-rest-api/node_modules/foxx-cli/lib/resolveToStream.js:44:20)
    at async Object.handler (/Users/work/Webstorm/arangodb-rest-api/node_modules/foxx-cli/lib/cmds/upgrade.js:152:9)

We apologize for the inconvenience.
```

Trying to specify the relative or absolute path to this directory as the optional parameter doesn't help either.
