### ISSUE TITLE
query parameter "mount" with value fails to match the required pattern

### ISSUE THREAD

**Issue by zainulabidin302** [arangodb/foxx-cli#35]
When i try to 
`$ foxx install --server dev ./ --database appdb`

I am getting this error
I have already setup dev
Unexpected ArangoDB error (Code: 400):
`query parameter "mount" with value ".&#x2f;" fails to match the required pattern: /(?:\/[-_0-9a-z]+)+/i`

Any help is appreciated.

**Comment by Simran-B** [comment]
Your command doesn't look right. Do you want to use the current working directory? Then `./` is not needed (it's the default), but a mounting path is always required. A mounting path could be something like `/hello-world`:

    foxx install --server dev --database appdb /hello-world

**Comment by pluma** [comment]
I'm closing this as I believe Simran's reply solves this and we haven't heard from you back in a while.
