### ISSUE TITLE
Foxx upgrade error on Gitlab-runner

### ISSUE THREAD

**Issue by mindaugasnakrosis** [arangodb/foxx-cli#36]
I am using gitlab-runner for CI/CD. I get error while trying to upgrade a service on pipeline.

The same command works when I execute it locally - not on gitlab-runner.
```
Running with gitlab-runner 11.7.0 (8bb608ff)
  on ci Xrx1zKeK
Using Docker executor with image node:11.7.0 ...
Pulling docker image node:11.7.0 ...
Using docker image sha256:7d3b4aa102297eb27045a4abf42a0bf024fba1f9a626a71e567b55641e79b590 for node:11.7.0 ...
Running on runner-Xrx1zKeK-project-3222783-concurrent-0 via ci...
Fetching changes...
Removing .cache/
Removing node_modules/
Checking out source
$ yarn global add foxx-cli
yarn global v1.13.0
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "foxx-cli@1.3.0" with binaries:
      - foxx
Done in 10.75s.
$ foxx upgrade /graphql ./packages/user/service/foxx --server http://root:xxxxxxx@myserverip:8529 -D ccio_dev
Sorry! An unexpected error occurred. This is likely a bug in foxx-cli.
Please open an issue at https://github.com/arangodb/foxx-cli/issues with a full copy of the following error message and a description of what you were trying to do when this problem occured.

Error: connect EHOSTUNREACH myserverip:8529
```

**Comment by pluma** [comment]
The error Foxx CLI encountered is "EHOSTUNREACH", which means the host is unreachable, for host "myserverip:8529". This means that when you ran the `foxx upgrade` command the ArangoDB instance you tried to talk to was unreachable from where you ran the command.

This may be a networking problem. I'm not intimately familiar with GitLab or Docker but your GitLab runner likely lives on an isolated network and has no way to access the ArangoDB server.

**Comment by pluma** [comment]
I'm closing this question due to inactivity. Feel free to reopen with additional information if you need further assistance.
