### ISSUE TITLE
Setting Servers

### ISSUE THREAD

**Issue by yq605879396** [arangodb/foxx-cli#44]
When I command "foxx install /hello-foxx", it shows "Server refused authorization. Either your credentials are invalid or the user has insufficient privileges." Should I set up a server or do anything else?

**Comment by ermanolca** [comment]
You need to use url pattern in your server url. Let's say you need to install your service to arangodb on localhost with root user and a password like 123456 you need to add parameter below

--server http://root:123456@localhost:8529

**Comment by pluma** [comment]
If you have not specified any credentials, Foxx CLI will default to using the `root` user with no password.

You can either specify credentials via `--username` and `--password` (which will read a password from STDIN) or `--password-file` (which expects a path to a file containing the password), or you can define a server configuration using the `server` commands and specify that server by name using `--server`.

**Comment by pluma** [comment]
I'm closing this question due to inactivity. Feel free to reopen with additional information if you need further assistance.
