### ISSUE TITLE
hapijs error

### ISSUE THREAD

**Issue by ermanolca** [arangodb/foxx-cli#45]
Even though i have added node_modules/joi and node_modules/@hapi to ignore list install command gives me error below: 

`Server encountered errors executing a JavaScript file:

@ node_modules\@hapi\address\lib\domain.js:14:21
  12 |     tldSegmentRx: /^[a-zA-Z](?:[a-zA-Z0-9\-]*[a-zA-Z0-9])?$/,
  13 |     domainSegmentRx: /^[a-zA-Z0-9](?:[a-zA-Z0-9\-]*[a-zA-Z0-9])?$/,
> 14 |     URL: Url.URL || URL                                                                 // $lab:coverage:ignore$
     |                     ^
  15 | };
  16 | 
  17 | 
ArangoError 3103: failed to invoke module
Reason: ReferenceError: URL is not defined
File: C:\Windows\TEMP\arangod_a06176\services-tmp-4780-528358610\node_modules\@hapi\address\lib\domain.js

For details check the arangod server logs.`

I am using arangodb community edition 3.6.4 and foxx_cli 2.0.0.

**Comment by pluma** [comment]
Can you show your directory structure and the contents of the ignore file?

**Comment by pluma** [comment]
This might be caused by the ignore file not being used reliably: #46.
