### ISSUE TITLE
TypeError: db.useDatabase is not a function

### ISSUE THREAD

**Issue by solisoft** [arangodb/foxx-cli#50]
within foxx v2.1.0

```
foxx install -D db_bw --server sw_fasty /settings settings
Sorry! An unexpected error occurred. This is likely a bug in foxx-cli.
Please open an issue at https://github.com/arangodb/foxx-cli/issues with a full copy of the following error message and a description of what you were trying to do when this problem occurred.

TypeError: db.useDatabase is not a function
    at module.exports (/Users/olivierbonnaure/.nvm/versions/node/v16.15.0/lib/node_modules/foxx-cli/lib/util/client.js:7:8)
    at Object.handler (/Users/olivierbonnaure/.nvm/versions/node/v16.15.0/lib/node_modules/foxx-cli/lib/cmds/install.js:136:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

We apologize for the inconvenience.
```

**Comment by solisoft** [comment]
Just a notice it occurs with nodejs 16

**Comment by solisoft** [comment]
Just tested with LTS v18.12.1 ... same issue

**Comment by solisoft** [comment]
Just tested with LTS v18.12.1 ... same issue

**Comment by solisoft** [comment]
Just tested with LTS v18.12.1 ... same issue

**Comment by HardikKSavaliya** [comment]
Facing an same issue with Node 18.12.0

**Comment by ghost** [comment]
Yes, this was a bug introduced during the upgrade to arangojs 8. Apparently none of the tests actually triggered the code using a different database. I've added a test that does that and fixed the bug.

**Comment by solisoft** [comment]
It's working now thanks !
<img width="290" alt="Capture d’écran 2022-11-28 à 09 50 01" src="https://user-images.githubusercontent.com/6237/204234058-02bc4280-d131-49c5-8d35-4e51e1e1b075.png">
